import type { FoodLibraryItem } from "../types/nutrition.types";

/** Built-in food catalog (no server table required for MVP). */
export const FOOD_SEARCH_SEED: FoodLibraryItem[] = [
  {
    id: "f1",
    user_id: null,
    name: "Chicken Breast (grilled)",
    cal: 165,
    protein: 31,
    carbs: 0,
    fat: 3.6,
    serving_size: 100,
    serving_unit: "g",
    barcode: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "f2",
    user_id: null,
    name: "Greek Yogurt",
    cal: 100,
    protein: 17,
    carbs: 6,
    fat: 0.7,
    serving_size: 170,
    serving_unit: "g",
    barcode: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "f3",
    user_id: null,
    name: "Brown Rice",
    cal: 216,
    protein: 5,
    carbs: 45,
    fat: 1.8,
    serving_size: 195,
    serving_unit: "g",
    barcode: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "f4",
    user_id: null,
    name: "Banana",
    cal: 105,
    protein: 1.3,
    carbs: 27,
    fat: 0.4,
    serving_size: 1,
    serving_unit: "medium",
    barcode: null,
    created_at: new Date().toISOString(),
  },
  {
    id: "f5",
    user_id: null,
    name: "Salmon Fillet",
    cal: 280,
    protein: 39,
    carbs: 0,
    fat: 12,
    serving_size: 154,
    serving_unit: "g",
    barcode: null,
    created_at: new Date().toISOString(),
  },
];
